### ISSUE TITLE
Going back to fxml?

### ISSUE THREAD

**Issue by tran-tien-dat** [cs2103jan2016-v15-1j/main#165]
The current GUI code has achieved a level of complexity that hinders readability. Currently, it feels similar to making a webpage not with html but by using purely javascript. I think we should separate the view and the controller here by using fxml, just like how webpages use html to express the views and javascript to encode behaviours.

However, I know this would be a time-consuming effort, so @SorataYuu should decide whether he wants to do it.

**Comment by tran-tien-dat** [comment]
Another advantage of fxml: easier for teammates to comment on the layout and how it can be improved!

**Comment by SorataYuu** [comment]
I understand where you're coming from. But the thing is that to convert to FXML I would have to overhaul the entire UI from scratch. Plus most elements are generated dynamically on the fly which is not doable in FXML. Plus ControlsFX controls are not supported in the SceneBuilder applications.
