### ISSUE TITLE
controlfx and jfoenix?

### ISSUE THREAD

**Issue by tran-tien-dat** [cs2103jan2016-v15-1j/main#170]
Is it necessary to use both libs? I would expect jfoenix to provide the complete set of control elements that are provided by controlfx

**Comment by SorataYuu** [comment]
Yes it is, they provide different components. JFoenix is purely design based and offers no new components. ControlsFX offers new components

**Comment by tran-tien-dat** [comment]
@SorataYuu I think it's because jfoenix is still in beta so it does not have too many features. Do you need to use any of jfoenix's component? (you said it offers no new components) If not can we just use jfoenix's css file and not including its jar lib?

**Comment by SorataYuu** [comment]
@tran-tien-dat I'm using their buttons, checkbox and textfield that has animations nt controlled just by CSS.
