### ISSUE TITLE
Implement GUI to allow user to specify data storage location

### ISSUE THREAD

**Issue by tran-tien-dat** [cs2103jan2016-v15-1j/main#172]
The ability to specify a specific file path as the data storage location. With this feature, Jim can choose to store the data file in a local folder controlled by a cloud syncing service (e.g. dropbox), allowing him to access task data from multiple computers. 
@cs2103jan2016-v15-1j/developers we totally forgot about this >.<

**Comment by shaunthium** [comment]
@SorataYuu gotta implement GUI for this (e.g. show current save file path in `help`)
