### ISSUE TITLE
Event should also be mark done - able

### ISSUE THREAD

**Issue by tran-tien-dat** [cs2103jan2016-v15-1j/main#180]
@cs2103jan2016-v15-1j/developers 
Due to this change, i think we should reorganize the model classes as follow:

- `TaskEvent` having both `name` and `completed`
- `FloatingTask`, `DeadlineTask` and `Event` all inherit from `TaskEvent`

Thus we'll delete the type `Task` which used to hold the `completed` property. Any comments?

**Comment by shaunthium** [comment]
Sounds good to me!

On Tuesday, 29 March 2016, Tran Tien Dat <notifications@github.com> wrote:

> @cs2103jan2016-v15-1j/developers
> <https://github.com/orgs/cs2103jan2016-v15-1j/teams/developers>
> Due to this change, i think we should reorganize the model classes as
> follow:
>
>    - TaskEvent having both name and completed
>    - FloatingTask, DeadlineTask and Event all inherit from TaskEvent
>
> Thus we'll delete the type Task which used to hold the completed
> property. Any comments?
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cs2103jan2016-v15-1j/main/issues/180>
>


-- 

Shaun Thium (Mr.)
*National University of Singapore*
B.Comp (Computer Science) | University Scholar's Programme
