### ISSUE TITLE
Multiple help page

### ISSUE THREAD

**Issue by tran-tien-dat** [cs2103jan2016-v15-1j/main#187]
@cs2103jan2016-v15-1j/developers 
As we are adding more and more syntax, one page help is definitely not enough space to explain them all. Hence we will need and index help that lists out the possible help command that the user can also use. My proposal:

- `help`: list all other possible `help` command
- `help common`: list down most commonly used syntax
- `help add`: list down syntax to add tasks/events. Similarly for other command
- `help date`: list down different date format the parser understand
- `help time`: list down different time format the parser understand

Thoughts?

**Comment by SorataYuu** [comment]
Seems fine to me, would be more intuitive too

**Comment by tran-tien-dat** [comment]
Temporary help pages:
- `index`: all possible `help` command
- `common`: most commonly used syntax
- `add`
- `delete`
- `mark`
- `unmark`
- `date`
- `time`
- `change`
- `search`
- `filter`
- `alias`
