### ISSUE TITLE
Revisiting `this tuesday` and `next tuesday`

### ISSUE THREAD

**Issue by tran-tien-dat** [cs2103jan2016-v15-1j/main#188]
@cs2103jan2016-v15-1j/developers 
Since their meanings are debatable, let's just go with the one that requires the least work for me, i.e. interpreting both the same as `tuesday` i.e. the first tuesday after today. Opinions?

**Comment by shaunthium** [comment]
I think you should just implement `this tuesday`, as that is not as up for debate.
